"""Human-readable gathering + planning. `plan` produces a detailed, written placement
plan from the netlist + schematic grouping — the "think before you place" artifact."""
from .graph import is_passive, kind_of


def gather(parts, graph, topo):
    """Structured facts about the board (components, nets, groups) as a dict."""
    from collections import Counter, defaultdict
    kinds = Counter(kind_of(r) for r in parts)
    sheets = defaultdict(list)
    for r in parts:
        sheets[parts[r].get("sheet", "root")].append(r)
    big = sorted([r for r in parts if parts[r]["w"] * parts[r]["h"] > 150],
                 key=lambda r: -parts[r]["w"] * parts[r]["h"])
    return dict(
        n_parts=len(parts), kinds=dict(kinds),
        n_signal=len(graph.signal_nets), n_power=len(graph.power_nets),
        sheets={s: len(v) for s, v in sheets.items()},
        big_parts=[(r, round(parts[r]["w"]), round(parts[r]["h"])) for r in big],
        hub=topo.hub, forks=topo.forks, isolated=topo.isolated,
    )


def plan_markdown(parts, graph, topo, strategy="pack", rotate="ortho"):
    g = gather(parts, graph, topo)
    L = []
    L.append(f"# Placement plan — {g['n_parts']} components\n")
    L.append(f"_Auto-generated by fluxplace from the netlist + schematic sheets._\n")

    L.append("## 1. What's on the board")
    L.append(f"- **{g['n_parts']} components**: " +
             ", ".join(f"{n}×{k}" for k, n in sorted(g["kinds"].items(), key=lambda x: -x[1])))
    L.append(f"- **{g['n_signal']} signal nets**, {g['n_power']} power/ground nets "
             f"(power excluded from the flow graph — routed as planes).")
    if g["big_parts"]:
        L.append("- **Anchors (large parts, orientation locked):** " +
                 ", ".join(f"`{r}` {w}×{h}mm" for r, w, h in g["big_parts"]))
    L.append("")

    L.append("## 2. Communication structure")
    L.append(f"- **Hub (trunk):** `{g['hub']}` — everything of consequence talks to it.")
    L.append(f"- **Fork points (deg≥3):** {', '.join('`%s`' % f for f in g['forks']) or 'none'}")
    if g["isolated"]:
        L.append(f"- **⚠ No signal lanes:** {', '.join('`%s`' % i for i in g['isolated'])} "
                 f"— power-only parts, or a wiring bug worth checking.")
    L.append("")

    L.append("## 3. Subsystem groups (schematic sheets → placement clusters)")
    L.append("Each sheet becomes one packed cluster so decoupling caps stay on their IC:")
    L.append("")
    L.append("| Cluster | Parts | Key devices |")
    L.append("|---|--:|---|")
    from collections import defaultdict
    by_sheet = defaultdict(list)
    for r in parts:
        by_sheet[parts[r].get("sheet", "root")].append(r)
    for b in topo.branches:
        sheet = parts[b.root].get("sheet", "root") if b.root in parts else "?"
    for sheet, refs in sorted(by_sheet.items(), key=lambda x: -len(x[1])):
        keys = [r for r in refs if not is_passive(r)]
        L.append(f"| `{sheet}` | {len(refs)} | {', '.join(keys[:6]) or '—'} |")
    L.append("")

    L.append("## 4. Signal-flow branches (placement order edge→hub)")
    for b in topo.branches:
        if len(b) < 2:
            continue
        flow = " → ".join(r for r in b.order if not is_passive(r)) or b.root
        tag = "→hub" if b.to_hub else "(local)"
        L.append(f"- **{b.root}** {tag}, {len(b)} parts: {flow}")
    L.append("")

    L.append("## 5. Placement strategy")
    L.append(f"- **Strategy:** `{strategy}` — " + {
        "pack": "cluster by sheet, pack each tight in signal order, bin-pack the clusters "
                "by connectivity into a compact rectangle.",
        "flux": "pin-aware force-directed: pull every pad toward its net's centroid; "
                "minimises weighted wirelength for the densest, most-routable result.",
        "radial": "hub centered, branches radiate to their edge connectors.",
    }.get(strategy, strategy))
    L.append(f"- **Rotation:** `{rotate}` — " + {
        "ortho": "snap to 0/90/180/270 for cheap, error-proof pick-and-place.",
        "fine": "any angle to align a part along its trace (lowest wirelength, less standard).",
        "none": "keep drawn orientation.",
    }.get(rotate, rotate))
    L.append("- **DFM rules applied:** courtyard clearance kept; decoupling caps clustered "
             "with their IC; large modules/connectors are keep-out obstacles (nothing under "
             "them) with locked orientation; board outline shrink-wrapped to the placement.")
    L.append("- **Quality metric:** weighted half-perimeter wirelength (HPWL). Lower = denser "
             "+ shorter traces = easier autorouting.")
    L.append("")
    return "\n".join(L)
